language: rust
cache: cargo
before_script:
  - cargo install -f rustfmt
  - export PATH=$PATH:$HOME/.cargo/bin
rust:
  - stable
  - beta
  - nightly

script:
  - cargo fmt -- --write-mode=diff
  - cargo test

matrix:
  allow_failures:
    - rust: nightly
