language: rust
cache: cargo
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgoogle-perftools-dev
rust:
  - stable
  - beta
  - nightly

script:
  - cargo test

matrix:
  allow_failures:
    - rust: nightly
